name: Unit Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
        working-directory: ./illust_record_f
      - name: npm run test
        run: npm run test
        working-directory: ./illust_record_f
